# Generated by Django 2.2.10 on 2021-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210325_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(db_index=True, default=None, max_length=500, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(default=None, max_length=500, verbose_name='Описание опроса'),
        ),
    ]
