# Generated by Django 2.2.10 on 2021-03-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210330_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(related_name='survey_answers', to='api.Answer', verbose_name='Ответы')),
                ('questions', models.ManyToManyField(related_name='survey_answers', to='api.Question', verbose_name='Вопросы')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_answers', to='api.Survey', verbose_name='Опросник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='api.User', verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опрос',
                'ordering': ['pk'],
            },
        ),
    ]
