# Generated by Django 2.2.10 on 2021-03-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_surveyanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
